### ISSUE TITLE
Resolve Children Before Throwing Lookup Exception

### ISSUE THREAD

**Issue by tjwiebell** [magento-research/upward-php#33]
# Problem #
A use case came up when developing the Proxy resolver where the config below would cause the error `No definition for response.status`. The logic in DefinitionIterator decides to throw an exception before resolving the parent key `response`, which is expected to populate the context with these keys (that's not entirely accurate with Proxy, since it short circuits the request, but this should be the assumption). 

```
status: response.status
headers: response.headers
body: response.body

response:
  resolver: proxy

proxy:
  target: env.MAGENTO_BACKEND_URL
  ignoreSSLErrors:
    inline: true
```

### AC ###
* The above config successfully serves a Proxy request
* Validation still exists where if after parent resolution and a key still doesn't exist, throw an exception
